package com.otio.backend.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalTime;

import com.otio.backend.model.Activity;
import com.otio.backend.model.ArtsCulture;
import com.otio.backend.model.Dining;
import com.otio.backend.model.Entertainment;
import com.otio.backend.model.Nightlife;
import com.otio.backend.model.Outdoor;
import com.otio.backend.model.Wellness;
import com.otio.backend.repo.ActivityRepo;
import com.otio.backend.repo.ArtsCultureRepo;
import com.otio.backend.repo.DiningRepo;
import com.otio.backend.repo.EntertainmentRepo;
import com.otio.backend.repo.NightlifeRepo;
import com.otio.backend.repo.OutdoorRepo;
import com.otio.backend.repo.UserRepo;
import com.otio.backend.repo.WellnessRepo;

import jakarta.annotation.PostConstruct;

@Service
public class AdminService {
    Logger logger = LoggerFactory.getLogger(AdminService.class);

    @Autowired
    ActivityRepo activityRepo;
    
    @Autowired
    DiningRepo diningRepo;

    @Autowired
    EntertainmentRepo entertainmentRepo;

    @Autowired
    ArtsCultureRepo artsCultureRepo;

    @Autowired
    NightlifeRepo nightLifeRepo;

    @Autowired
    OutdoorRepo outdoorRepo;

    @Autowired
    WellnessRepo wellnessRepo;

    @Autowired
    UserRepo userRepo;

    @PostConstruct
    public void init() {
        logger.info("Initializing the service...");
        Activity restaurant1 = new Dining("DNN01", "Kaen Sushi", "Restaurant", "DNN01.png", 4.6, "DNN01path", "https://maps.app.goo.gl/NJmmdPC9AqApN1Ho9");
        restaurant1.addTimeSlot(LocalTime.of(12, 0, 0));
        restaurant1.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(restaurant1);
        diningRepo.save((Dining)restaurant1);
        Activity restaurant2 = new Dining("DNN02", "House of B", "Restaurant", "DNN02.png", 4.6, "DNN02path", "https://maps.app.goo.gl/TWgTkqPzszpmrVjJ7");
        restaurant2.addTimeSlot(LocalTime.of(11, 30, 0));
        restaurant2.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(restaurant2);
        diningRepo.save((Dining)restaurant2);
        Activity restaurant3 = new Dining("DNN03", "Emporio Ristorante", "Restaurant", "DNN03.jpg", 4.7, "DNN03path", "https://maps.app.goo.gl/Y3YoQnyRKhJKgjpE7");
        restaurant3.addTimeSlot(LocalTime.of(12, 0, 0));
        restaurant3.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(restaurant3);
        diningRepo.save((Dining)restaurant3);
        Activity restaurant4 = new Dining("DNN04", "Oklava Taze Makarna", "Restaurant", "DNN04.jpg", 4.4, "DNN04path", "https://maps.app.goo.gl/yNL6Zy4EX8w2r7LR8");
        restaurant4.addTimeSlot(LocalTime.of(12, 0, 0));
        restaurant4.addTimeSlot(LocalTime.of(21, 30, 0));
        activityRepo.save(restaurant4);
        diningRepo.save((Dining)restaurant4);
        Activity restaurant5 = new Dining("DNN05", "Sendika Beyoğlu", "Restaurant", "DNN05.jpg", 4.3, "DNN05path", "https://maps.app.goo.gl/vJQdjczSZsjysjxEA");
        restaurant5.addTimeSlot(LocalTime.of(18, 0, 0));
        restaurant5.addTimeSlot(LocalTime.of(3, 0, 0));
        activityRepo.save(restaurant5);
        diningRepo.save((Dining)restaurant5);

        Activity cafe1 = new Dining("DNN06", "Story Coffee & Food", "Cafe", "DNN06.png", 4.4, "DNN06path", "https://maps.app.goo.gl/yBFUNKT3z4ZVoTgk7");
        cafe1.addTimeSlot(LocalTime.of(9, 0, 0));
        cafe1.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(cafe1);
        diningRepo.save((Dining)cafe1);
        Activity cafe2 = new Dining("DNN07", "Meet Lab Coffee", "Cafe", "DNN07.jpg", 4.5, "DNN07path", "https://maps.app.goo.gl/5686vuaPeNSwe6MR6");
        cafe2.addTimeSlot(LocalTime.of(8, 0, 0));
        cafe2.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(cafe2);
        diningRepo.save((Dining)cafe2);
        Activity cafe3 = new Dining("DNN08", "frunch", "Cafe", "DNN08.jpg", 5.0, "DNN08path", "https://maps.app.goo.gl/HHAQJmWTqtckUFeA8");
        cafe3.addTimeSlot(LocalTime.of(9, 0, 0));
        cafe3.addTimeSlot(LocalTime.of(18, 0, 0));
        activityRepo.save(cafe3);
        diningRepo.save((Dining)cafe3);
        Activity cafe4 = new Dining("DNN09", "Kara Kedi Coffee Lotus", "Cafe", "DNN09.jpeg", 4.8, "DNN09path", "https://maps.app.goo.gl/Ht9VGBvztYcx3wBdA");
        cafe4.addTimeSlot(LocalTime.of(11, 0, 0));
        cafe4.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(cafe4);
        diningRepo.save((Dining)cafe4);
        Activity cafe5 = new Dining("DNN10", "Manu Bakery & Eatery", "Cafe", "DNN10.jpg", 4.9, "DNN10path", "https://maps.app.goo.gl/bp2xo8n4XGcTvswj7");
        cafe5.addTimeSlot(LocalTime.of(9, 0, 0));
        cafe5.addTimeSlot(LocalTime.of(0, 0, 0));
        activityRepo.save(cafe5);
        diningRepo.save((Dining)cafe5);

        Activity finedining1 = new Dining("DNN11", "Strada", "Fine Dining", "DNN11.png", 4.2, "DNN11path", "https://maps.app.goo.gl/UHfj7RHSSGh6MMEw5");
        finedining1.addTimeSlot(LocalTime.of(12, 0, 0));
        finedining1.addTimeSlot(LocalTime.of(0, 0, 0));
        activityRepo.save(finedining1);
        diningRepo.save((Dining)finedining1);
        Activity finedining2 = new Dining("DNN12", "MSA Culinary School Restaurant", "Fine Dining", "DNN12.jpg", 4.2, "DNN12path", "https://maps.app.goo.gl/Vqdvxnn2tPxG3NLp6");
        finedining2.addTimeSlot(LocalTime.of(8, 0, 0));
        finedining2.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(finedining2);
        diningRepo.save((Dining)finedining2);
        Activity finedining3 = new Dining("DNN13", "Olden 1772", "Fine Dining", "DNN13.JPG", 4.6, "DNN13path", "https://maps.app.goo.gl/p2YWmNAcSTJgSVKT6");
        finedining3.addTimeSlot(LocalTime.of(9, 0, 0));
        finedining3.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(finedining3);
        diningRepo.save((Dining)finedining3);
        Activity finedining4 = new Dining("DNN14", "Cuma", "Fine Dining", "DNN14.JPG", 4.2, "DNN14path", "https://maps.app.goo.gl/5psRyDk1dY2d79mV6");
        finedining4.addTimeSlot(LocalTime.of(9, 0, 0));
        finedining4.addTimeSlot(LocalTime.of(0, 0, 0));
        activityRepo.save(finedining4);
        diningRepo.save((Dining)finedining4);
        Activity finedining5 = new Dining("DNN15", "Sapa İstanbul", "Fine Dining", "DNN15.png", 4.6, "DNN15path", "https://maps.app.goo.gl/MQeT1zibbh4AAdkWA");
        finedining5.addTimeSlot(LocalTime.of(10, 0, 0));
        finedining5.addTimeSlot(LocalTime.of(0, 0, 0));
        activityRepo.save(finedining5);
        diningRepo.save((Dining)finedining5);


        Activity concert1 = new Entertainment("ENT01", "Bostanci Show Center", "Concerts", "ENT01.jpg", 4.0, "ENT01path", "https://maps.app.goo.gl/ke1kBMnY2wyUP9Uz5");
        concert1.addTimeSlot(LocalTime.of(7, 0, 0));
        concert1.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(concert1);
        entertainmentRepo.save((Entertainment)concert1);
        Activity concert2 = new Entertainment("ENT02", "KüçükÇiftlik Park", "Concerts", "ENT02.jpg", 4.2, "ENT02path", "https://maps.app.goo.gl/tg6MntF8APfUsGN5A");
        concert2.addTimeSlot(LocalTime.of(7, 0, 0));
        concert2.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(concert2);
        entertainmentRepo.save((Entertainment)concert2);
        Activity concert3 = new Entertainment("ENT03", "Volkswagen Arena", "Concerts", "ENT03.jpg", 4.5, "ENT03path", "https://maps.app.goo.gl/Vi2ug61BxgS39EVW7");
        concert3.addTimeSlot(LocalTime.of(12, 30, 0));
        concert3.addTimeSlot(LocalTime.of(6, 30, 0));
        activityRepo.save(concert3);
        entertainmentRepo.save((Entertainment)concert3);
        Activity concert4 = new Entertainment("ENT04", "Zorlu Performing Arts Center", "Concerts", "ENT04.jpg", 4.6, "ENT04path", "https://maps.app.goo.gl/vWW8YatJhPY2ET4E8");
        concert4.addTimeSlot(LocalTime.of(7, 0, 0));
        concert4.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(concert4);
        entertainmentRepo.save((Entertainment)concert4);
        Activity concert5 = new Entertainment("ENT05", "Dorock XL Kadıköy", "Concerts", "ENT05.jpg", 4.0, "ENT05path", "https://maps.app.goo.gl/awpm8F9j9yvt5We16");
        concert5.addTimeSlot(LocalTime.of(7, 0, 0));
        concert5.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(concert5);
        entertainmentRepo.save((Entertainment)concert5);

        Activity movie1 = new Entertainment("ENT06", "Ckm Sineması", "Movies", "ENT06.jpg", 4.1, "ENT06path", "https://maps.app.goo.gl/U53tSZBK9gLjXMkEA");
        movie1.addTimeSlot(LocalTime.of(10, 0, 0));
        movie1.addTimeSlot(LocalTime.of(22, 0, 0));
        activityRepo.save(movie1);
        entertainmentRepo.save((Entertainment)movie1);
        Activity movie2 = new Entertainment("ENT07", "Cinehouse Kadıköy", "Movies", "ENT07.jpg", 4.9, "ENT07path", "https://maps.app.goo.gl/JigVVKgTPnxt6yHn9");
        movie2.addTimeSlot(LocalTime.of(11, 0, 0));
        movie2.addTimeSlot(LocalTime.of(22, 0, 0));
        activityRepo.save(movie2);
        entertainmentRepo.save((Entertainment)movie2);
        Activity movie3 = new Entertainment("ENT08", "Kadıköy Sineması", "Movies", "ENT08.jpg", 4.3, "ENT08path", "https://maps.app.goo.gl/U3nvF9iumsgjeYPk9");
        movie3.addTimeSlot(LocalTime.of(10, 0, 0));
        movie3.addTimeSlot(LocalTime.of(22, 0, 0));
        activityRepo.save(movie3);
        entertainmentRepo.save((Entertainment)movie3);
        Activity movie4 = new Entertainment("ENT09", "Capitol Spectrum Cineplex", "Movies", "ENT09.jpg", 4.4, "ENT09path", "https://maps.app.goo.gl/WCBSpfymgGaFLxw59");
        movie4.addTimeSlot(LocalTime.of(10, 0, 0));
        movie4.addTimeSlot(LocalTime.of(22, 0, 0));
        activityRepo.save(movie4);
        entertainmentRepo.save((Entertainment)movie4);
        Activity movie5 = new Entertainment("ENT10", "Alkazar Sineması", "Movies", "ENT10.jpg", 4.8, "ENT10path", "https://maps.app.goo.gl/o6AGSwVXPULMUojP7");
        movie5.addTimeSlot(LocalTime.of(10, 0, 0));
        movie5.addTimeSlot(LocalTime.of(22, 0, 0));
        activityRepo.save(movie5);
        entertainmentRepo.save((Entertainment)movie5);

        Activity comedy1 = new Entertainment("ENT11", "BKM Mutfak Sahne", "Comedy Shows", "ENT11.png", 4.5, "ENT11path", "https://maps.app.goo.gl/M67EX4nf9GJpNBVM8");
        comedy1.addTimeSlot(LocalTime.of(0, 0, 0));
        comedy1.addTimeSlot(LocalTime.of(23, 59, 0));
        activityRepo.save(comedy1);
        entertainmentRepo.save((Entertainment)comedy1);
        Activity comedy2 = new Entertainment("ENT12", "TuzBiber Komedi Kulübü", "Comedy Shows", "ENT12.jpeg", 3.2, "ENT12path", "https://maps.app.goo.gl/45dM8REVTqvqVo8A6");
        comedy2.addTimeSlot(LocalTime.of(12, 0, 0));
        comedy2.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(comedy2);
        entertainmentRepo.save((Entertainment)comedy2);
        Activity comedy3 = new Entertainment("ENT13", "Infiniti Sahne", "Comedy Shows", "ENT13.jpg", 4.2, "ENT13path", "https://maps.app.goo.gl/Jx9VR8ioNUQHtPR48");
        comedy3.addTimeSlot(LocalTime.of(20, 0, 0));
        comedy3.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(comedy3);
        entertainmentRepo.save((Entertainment)comedy3);
        Activity comedy4 = new Entertainment("ENT14", "Efsahne Beyoğlu", "Comedy Shows", "ENT14.jpg", 4.0, "ENT14path", "https://maps.app.goo.gl/49eoSSyewGxeAxXEA");
        comedy4.addTimeSlot(LocalTime.of(20, 0, 0));
        comedy4.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(comedy4);
        entertainmentRepo.save((Entertainment)comedy4);
        Activity comedy5 = new Entertainment("ENT15", "Caddebostan Cultural Center (CKM)", "Comedy Shows", "ENT15.jpg", 4.3, "ENT15path", "https://maps.app.goo.gl/VLsaQmkQrDcW84fB8");
        comedy5.addTimeSlot(LocalTime.of(19, 0, 0));
        comedy5.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(comedy5);
        entertainmentRepo.save((Entertainment)comedy5);

        Activity spa1= new Wellness("WEL01", "E Spa Wellness & Kadıköy Massage, Turkish Bath Therapy", "Spas and Massage Studios", "WEL01.jpg", 4.8, "WEL01path", "https://maps.app.goo.gl/JQfxkk5H2dBvkhK39");
        spa1.addTimeSlot(LocalTime.of(10, 0, 0));
        spa1.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(spa1);
        wellnessRepo.save((Wellness)spa1);
        Activity spa2= new Wellness("WEL02", "Pasha SPA & Wellness", "Spas and Massage Studios", "WEL02.jpg", 4.7, "WEL02path", "https://maps.app.goo.gl/xQxm8DPSnkBaCRwo9");
        spa2.addTimeSlot(LocalTime.of(9, 0, 0));
        spa2.addTimeSlot(LocalTime.of(0, 0, 0));
        activityRepo.save(spa2);
        wellnessRepo.save((Wellness)spa2);
        Activity spa3= new Wellness("WEL03", "Lilyum Spa and Wellness", "Spas and Massage Studios", "WEL03.jpg", 4.7, "WEL03path", "https://maps.app.goo.gl/eFUpAgTw8JB5FBsP6");
        spa3.addTimeSlot(LocalTime.of(10, 0, 0));
        spa3.addTimeSlot(LocalTime.of(0, 0, 0));
        activityRepo.save(spa3);
        wellnessRepo.save((Wellness)spa3);
        Activity spa4= new Wellness("WEL04", "Sarnıç Spa & Turkish Bath", "Spas and Massage Studios", "WEL04.jpeg", 4.8, "WEL04path", "https://maps.app.goo.gl/4P758tFs47rXk9Ub7");
        spa4.addTimeSlot(LocalTime.of(9, 0, 0));
        spa4.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(spa4);
        wellnessRepo.save((Wellness)spa4);
        Activity spa5= new Wellness("WEL05", "Felicity Spa Center", "Spas and Massage Studios", "WEL05.jpeg", 4.7, "WEL05path", "https://maps.app.goo.gl/FX8g9vwLfYFfS6Go7");
        spa5.addTimeSlot(LocalTime.of(12, 0, 0));
        spa5.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(spa5);
        wellnessRepo.save((Wellness)spa5);

        Activity yoga1= new Wellness("WEL06", "MyOttoYoga", "Pilates and Yoga Studios", "WEL06.jpg", 5.0, "WEL06path", "https://maps.app.goo.gl/rEyZsS8zVBREubEv5");
        yoga1.addTimeSlot(LocalTime.of(12, 0, 0));
        yoga1.addTimeSlot(LocalTime.of(22, 0, 0));
        wellnessRepo.save((Wellness)yoga1);
        activityRepo.save(yoga1);
        Activity yoga2= new Wellness("WEL07", "Simyfit Pilates ve Hamak Yogası", "Pilates and Yoga Studios", "WEL07.png", 5.0, "WEL07path", "https://maps.app.goo.gl/KotzXubwZ6gVepi9A");
        yoga2.addTimeSlot(LocalTime.of(7, 0, 0));
        yoga2.addTimeSlot(LocalTime.of(23, 0, 0));
        wellnessRepo.save((Wellness)yoga2);
        activityRepo.save(yoga2);
        Activity yoga3= new Wellness("WEL08", "Pilates Body Design", "Pilates and Yoga Studios", "WEL08.jpg", 4.9, "WEL08path", "https://maps.app.goo.gl/hkLt3njsWTc3jm8N7");
        yoga3.addTimeSlot(LocalTime.of(7, 30, 0));
        yoga3.addTimeSlot(LocalTime.of(22, 30, 0));
        wellnessRepo.save((Wellness)yoga3);
        activityRepo.save(yoga3);
        Activity yoga4= new Wellness("WEL09", "Githa Satya Yoga Merkezi", "Pilates and Yoga Studios", "WEL09.jpg", 4.8, "WEL09path", "https://maps.app.goo.gl/3C34XfwzkX6DBN93A");
        yoga4.addTimeSlot(LocalTime.of(10, 0, 0));
        yoga4.addTimeSlot(LocalTime.of(21, 0, 0));
        wellnessRepo.save((Wellness)yoga4);
        activityRepo.save(yoga4);
        Activity yoga5= new Wellness("WEL10", "Gymnasio Pilates", "Pilates and Yoga Studios", "WEL10.png", 4.9, "WEL10path", "https://maps.app.goo.gl/KcDM2PsfdArkCtsM8");
        yoga5.addTimeSlot(LocalTime.of(7, 0, 0));
        yoga5.addTimeSlot(LocalTime.of(21, 0, 0));
        wellnessRepo.save((Wellness)yoga5);
        activityRepo.save(yoga5);

        Activity museum1 = new ArtsCulture("ART01", "Istanbul Archaeology Museums", "Museums", "ART01.jpg", 4.6, "ART01path", "https://maps.app.goo.gl/Um77hkgQjR3dnsR98");
        museum1.addTimeSlot(LocalTime.of(9, 0, 0));
        museum1.addTimeSlot(LocalTime.of(18, 30, 0));
        activityRepo.save(museum1);
        artsCultureRepo.save((ArtsCulture)museum1);
        Activity museum2 = new ArtsCulture("ART02", "Sakıp Sabancı Museum", "Museums", "ART02.jpg", 4.7, "ART02path", "https://maps.app.goo.gl/Be4f4tWumtgVhQo88");
        museum2.addTimeSlot(LocalTime.of(10, 0, 0));
        museum2.addTimeSlot(LocalTime.of(18, 30, 0));
        activityRepo.save(museum2);
        artsCultureRepo.save((ArtsCulture)museum2);
        Activity museum3 = new ArtsCulture("ART03", "Pera Museum", "Museums", "ART03.jpg", 4.6, "ART03path", "https://maps.app.goo.gl/m8kjEtjdiaDEEXREA");
        museum3.addTimeSlot(LocalTime.of(10, 0, 0));
        museum3.addTimeSlot(LocalTime.of(19, 0, 0));
        activityRepo.save(museum3);
        artsCultureRepo.save((ArtsCulture)museum3);
        Activity museum4 = new ArtsCulture("ART04", "Istanbul Modern", "Museums", "ART04.jpg", 4.4, "ART04path", "https://maps.app.goo.gl/5HR3qvtQ3kq9rh1EA");
        museum4.addTimeSlot(LocalTime.of(10, 0, 0));
        museum4.addTimeSlot(LocalTime.of(18, 0, 0));
        activityRepo.save(museum4);
        artsCultureRepo.save((ArtsCulture)museum4);
        Activity museum5 = new ArtsCulture("ART05", "Museum of Innocence", "Museums", "ART05.jpg", 4.6, "ART05path", "https://maps.app.goo.gl/ycaLiBuzJGfBzx7dA");
        museum5.addTimeSlot(LocalTime.of(10, 0, 0));
        museum5.addTimeSlot(LocalTime.of(18, 0, 0));
        activityRepo.save(museum5);
        artsCultureRepo.save((ArtsCulture)museum5);

        Activity historicalSite1 = new ArtsCulture("ART06", "Dolmabahçe Palace", "Historical Sites", "ART11.jpg", 4.7, "ART11path", "https://maps.app.goo.gl/UMei2sviRHUxSPNM7");
        historicalSite1.addTimeSlot(LocalTime.of(9, 0, 0));
        historicalSite1.addTimeSlot(LocalTime.of(16, 0, 0));
        activityRepo.save(historicalSite1);
        artsCultureRepo.save((ArtsCulture)historicalSite1);
        Activity historicalSite2 = new ArtsCulture("ART07", "Basilica Cistern", "Historical Sites", "ART12.jpg", 4.6, "ART12path", "https://maps.app.goo.gl/E7z56wnnrjGhU2vRA");
        historicalSite2.addTimeSlot(LocalTime.of(9, 0, 0));
        historicalSite2.addTimeSlot(LocalTime.of(22, 0, 0));
        activityRepo.save(historicalSite2);
        artsCultureRepo.save((ArtsCulture)historicalSite2);
        Activity historicalSite3 = new ArtsCulture("ART08", "The Blue Mosque", "Historical Sites", "ART13.jpg", 4.7, "ART13path", "https://maps.app.goo.gl/UN4zx2qzLnR444KT7");
        historicalSite3.addTimeSlot(LocalTime.of(0, 0, 0));
        historicalSite3.addTimeSlot(LocalTime.of(23, 59, 0));
        activityRepo.save(historicalSite3);
        artsCultureRepo.save((ArtsCulture)historicalSite3);
        Activity historicalSite4 = new ArtsCulture("ART09", "Rumeli Fortress", "Historical Sites", "ART14.jpg", 4.5, "ART14path", "https://maps.app.goo.gl/cX2WLSWCnjqWE6Pb8");
        historicalSite4.addTimeSlot(LocalTime.of(9, 0, 0));
        historicalSite4.addTimeSlot(LocalTime.of(18, 0, 0));
        activityRepo.save(historicalSite4);
        artsCultureRepo.save((ArtsCulture)historicalSite4);
        Activity historicalSite5 = new ArtsCulture("ART10", "Topkapı Palace", "Historical Sites", "ART15.jpg", 4.7, "ART15path", "https://maps.app.goo.gl/Le4BUwf5cS74uJ8g7");
        historicalSite5.addTimeSlot(LocalTime.of(10, 0, 0));
        historicalSite5.addTimeSlot(LocalTime.of(16, 0, 0));
        activityRepo.save(historicalSite5);
        artsCultureRepo.save((ArtsCulture)historicalSite5);

        Activity theater1 = new ArtsCulture("ART11", "Moda Stage", "Theater", "ART16.jpg", 4.6, "ART16path", "https://maps.app.goo.gl/H5XdsRNY2n7B7ku39");
        theater1.addTimeSlot(LocalTime.of(14, 0, 0));
        theater1.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(theater1);
        artsCultureRepo.save((ArtsCulture)theater1);
        Activity theater2 = new ArtsCulture("ART12", "Atatürk Cultural Centre", "Theater", "ART17.jpg", 4.6, "ART17path", "https://maps.app.goo.gl/MTBkfXs5DUj885Hy8");
        theater2.addTimeSlot(LocalTime.of(10, 0, 0));
        theater2.addTimeSlot(LocalTime.of(22, 30, 0));
        activityRepo.save(theater2);
        artsCultureRepo.save((ArtsCulture)theater2);
        Activity theater3 = new ArtsCulture("ART13", "Süreyya Opera House", "Theater", "ART18.jpg", 4.8, "ART18path", "https://maps.app.goo.gl/THAofGQgzDKhQwxh9");
        theater3.addTimeSlot(LocalTime.of(11, 0, 0));
        theater3.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(theater3);
        artsCultureRepo.save((ArtsCulture)theater3);
        Activity theater4 = new ArtsCulture("ART14", "Baba Sahne", "Theater", "ART19.jpg", 4.8, "ART19path", "https://maps.app.goo.gl/MJx6fSyPZioHD1Kb8");
        theater4.addTimeSlot(LocalTime.of(16, 0, 0));
        theater4.addTimeSlot(LocalTime.of(22, 30, 0));
        activityRepo.save(theater4);
        artsCultureRepo.save((ArtsCulture)theater4);
        Activity theater5 = new ArtsCulture("ART15", "Kadıköy Sineması", "Theater", "ART20.jpg", 4.3, "ART20path", "https://maps.app.goo.gl/vnm7WMZR5thLJSWH6");
        theater5.addTimeSlot(LocalTime.of(12, 0, 0));
        theater5.addTimeSlot(LocalTime.of(0, 0, 0));
        activityRepo.save(theater5);
        artsCultureRepo.save((ArtsCulture)theater5);

        Activity bar1 = new Nightlife("NHT01","Alexandra Cocktail Bar","Bar","NHT01.jpg",3.7,"NHT01path","https://maps.app.goo.gl/khSk5F2tmmLWVLdp6");
        bar1.addTimeSlot(LocalTime.of(14, 0, 0));
        bar1.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(bar1);
        nightLifeRepo.save((Nightlife)bar1);
        Activity bar2 = new Nightlife("NHT02","monkeyistanbul","Bar","NHT02.jpg",3.8,"NHT02path","https://maps.app.goo.gl/mBEE3QWhpaLgUjRB9");
        bar2.addTimeSlot(LocalTime.of(18, 0, 0));
        bar2.addTimeSlot(LocalTime.of(2, 30, 0));
        activityRepo.save(bar2);
        nightLifeRepo.save((Nightlife)bar2);
        Activity bar3 = new Nightlife("NHT03","Mathilda's Cocktail Bar","Bar","NHT03.jpg",4.4,"NHT03path","https://maps.app.goo.gl/3BCPys4V9xpnW2ZK8");
        bar3.addTimeSlot(LocalTime.of(14, 0, 0));
        bar3.addTimeSlot(LocalTime.of(3, 0, 0));
        
        activityRepo.save(bar3);
        nightLifeRepo.save((Nightlife)bar3);
        Activity bar4 = new Nightlife("NHT04","Ernest's Bar","Bar","NHT04.jpg",4.9,"NHT04path","https://maps.app.goo.gl/TzxZYZ1v4eLsoFpE8");
        bar4.addTimeSlot(LocalTime.of(18, 0, 0));
        bar4.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(bar4);
        nightLifeRepo.save((Nightlife)bar4);
        Activity bar5 = new Nightlife("NHT05","Goose No.25","Bar","NHT05.jpg",3.7,"NHT05path","https://maps.app.goo.gl/DFFK2tFHHX6VasJK8");
        bar5.addTimeSlot(LocalTime.of(17, 0, 0));
        bar5.addTimeSlot(LocalTime.of(3, 0, 0));
        activityRepo.save(bar5);
        nightLifeRepo.save((Nightlife)bar5);

        Activity club1 = new Nightlife("NHT06","360 İstanbul","Club","NHT06.jpg",4.0,"NHT06path","https://maps.app.goo.gl/yy13zLavWLodoBZC8");
        club1.addTimeSlot(LocalTime.of(12, 0, 0));
        club1.addTimeSlot(LocalTime.of(4, 0, 0));
        activityRepo.save(club1);
        nightLifeRepo.save((Nightlife)club1);
        Activity club2 = new Nightlife("NHT07","Klein Harbiye","Club","NHT07.jpg",3.4,"NHT07path","https://maps.app.goo.gl/R7YPLPn9oHKxv8jZ7");
        club2.addTimeSlot(LocalTime.of(11, 0, 0));
        club2.addTimeSlot(LocalTime.of(5, 0, 0));
        activityRepo.save(club2);
        nightLifeRepo.save((Nightlife)club2);
        Activity club3 = new Nightlife("NHT08","Sortie","Club","NHT08.jpg",4.0,"NHT08path","https://maps.app.goo.gl/CoxNoudgPoF94Jik6");
        club3.addTimeSlot(LocalTime.of(18, 0, 0));
        club3.addTimeSlot(LocalTime.of(4, 0, 0));
        activityRepo.save(club3);
        nightLifeRepo.save((Nightlife)club3);
        Activity club4 = new Nightlife("NHT09","Sess Nişantaşı","Club","NHT09.jpg",3.3,"NHT09path","https://maps.app.goo.gl/fAsNsz4WC2UQ9vbw5");
        club4.addTimeSlot(LocalTime.of(22, 0, 0));
        club4.addTimeSlot(LocalTime.of(5, 0, 0));
        activityRepo.save(club4);
        nightLifeRepo.save((Nightlife)club4);
        Activity club5 = new Nightlife("NHT10","Jungle 8","Club","NHT10.jpg",3.5,"NHT10path","https://maps.app.goo.gl/AjtCwNEPxcSKmSEi8");
        club5.addTimeSlot(LocalTime.of(23, 30, 0));
        club5.addTimeSlot(LocalTime.of(4, 30, 0));
        activityRepo.save(club5);
        nightLifeRepo.save((Nightlife)club5);

        Activity karaoke1 = new Nightlife("NHT11","Sallash Karaoke Dans Bar","Karaoke","NHT11.jpg",3.9,"NHT11path","https://maps.app.goo.gl/uQzHbx6HCKsHSz5J6");
        karaoke1.addTimeSlot(LocalTime.of(12, 0, 0));
        karaoke1.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(karaoke1);
        nightLifeRepo.save((Nightlife)karaoke1);
        Activity karaoke2 = new Nightlife("NHT12","Red Lara","Karaoke","NHT12.jpg",4.3,"NHT12path","https://maps.app.goo.gl/sjqeYaJbVuyKjA2UA");
        karaoke2.addTimeSlot(LocalTime.of(12, 0, 0));
        karaoke2.addTimeSlot(LocalTime.of(1, 30, 0));
        activityRepo.save(karaoke2);
        nightLifeRepo.save((Nightlife)karaoke2);
        Activity karaoke3 = new Nightlife("NHT13","My Moon Karaoke Bar","Karaoke","NHT13.jpg",3.5,"NHT13path","https://maps.app.goo.gl/8YBxZ7YBWRvKCfxbA");
        karaoke3.addTimeSlot(LocalTime.of(15, 0, 0));
        karaoke3.addTimeSlot(LocalTime.of(4, 0, 0));
        activityRepo.save(karaoke3);
        nightLifeRepo.save((Nightlife)karaoke3);
        Activity karaoke4 = new Nightlife("NHT14","Lokka","Karaoke","NHT14.jpg",4.2,"NHT14path","https://maps.app.goo.gl/8A7iv1M3oBPjUfzA9");
        karaoke4.addTimeSlot(LocalTime.of(12, 0, 0));
        karaoke4.addTimeSlot(LocalTime.of(5, 0, 0));
        activityRepo.save(karaoke4);
        nightLifeRepo.save((Nightlife)karaoke4);
        Activity karaoke5 = new Nightlife("NHT15","Doremi Karaoke Bar","Karaoke","NHT15.jpg",4.7,"NHT15path","https://maps.app.goo.gl/jnNceZHDT8aWxmMF7");
        karaoke5.addTimeSlot(LocalTime.of(12, 0, 0));
        karaoke5.addTimeSlot(LocalTime.of(4, 0, 0));
        activityRepo.save(karaoke5);
        nightLifeRepo.save((Nightlife)karaoke5);

        Activity tavern1 = new Nightlife("NHT16","Agora Meyhanesi 1890","Tavern","NHT16.jpg",4.4,"NHT16path","https://maps.app.goo.gl/o2vVxnPaYYxHkxqr8");
        tavern1.addTimeSlot(LocalTime.of(13, 0, 0));
        tavern1.addTimeSlot(LocalTime.of(1,0, 0));
        activityRepo.save(tavern1);
        nightLifeRepo.save((Nightlife)tavern1);
        Activity tavern2 = new Nightlife("NHT17","İnciraltı Meyhanesi","Tavern","NHT17.jpg",4.4,"NHT17path","https://maps.app.goo.gl/VDk8ujsHhQbX4kzC6");
        tavern2.addTimeSlot(LocalTime.of(12, 0, 0));
        tavern2.addTimeSlot(LocalTime.of(21, 30, 0));
        activityRepo.save(tavern2);
        nightLifeRepo.save((Nightlife)tavern2);
        Activity tavern3 = new Nightlife("NHT18","Yakup2 Restaurant Beyoğlu","Tavern","NHT18.jpg",4.1,"NHT18path","https://maps.app.goo.gl/9dxsjHtexR9G76C27");
        tavern3.addTimeSlot(LocalTime.of(12, 0, 0));
        tavern3.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(tavern3);
        nightLifeRepo.save((Nightlife)tavern3);
        Activity tavern4 = new Nightlife("NHT19","HaNi Restaurant","Tavern","NHT19.jpg",4.5,"NHT19path","https://maps.app.goo.gl/9VTHaCX14aeDXKBm9");
        tavern4.addTimeSlot(LocalTime.of(15, 0, 0));
        tavern4.addTimeSlot(LocalTime.of(1, 0, 0));
        activityRepo.save(tavern4);
        nightLifeRepo.save((Nightlife)tavern4);
        Activity tavern5 = new Nightlife("NHT20","Adı Şahane Caddebostan","Tavern","NHT20.jpg",3.6,"NHT20path","https://maps.app.goo.gl/pfU4CBYjhFWfBfez5");
        tavern5.addTimeSlot(LocalTime.of(19, 0, 0));
        tavern5.addTimeSlot(LocalTime.of(2, 0, 0));
        activityRepo.save(tavern5);
        nightLifeRepo.save((Nightlife)tavern5);

        Activity hiking1 = new Outdoor("OUT01","Emirgan Korusu","Hiking","OUT01.jpg",4.6,"OUT01path","https://maps.app.goo.gl/PXMfaY7zpkArgjD39");
        hiking1.addTimeSlot(LocalTime.of(5, 0, 0));
        hiking1.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(hiking1);
        outdoorRepo.save((Outdoor)hiking1);
        Activity hiking2 = new Outdoor("OUT02","Turkcell Platinum Park","Hiking","OUT02.jpg",3.7,"OUT02path","https://maps.app.goo.gl/1cTUR9ibWA8w7bjA9");
        hiking2.addTimeSlot(LocalTime.of(9, 30, 0));
        hiking2.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(hiking2);
        outdoorRepo.save((Outdoor)hiking2);
        Activity hiking3 = new Outdoor("OUT03","Atatürk Arboretumu","Hiking","OUT03.jpg",4.6,"OUT03path","https://maps.app.goo.gl/PuxiT2J1rW46N9MN7");
        hiking3.addTimeSlot(LocalTime.of(8, 30, 0));
        hiking3.addTimeSlot(LocalTime.of(17, 0, 0));
        activityRepo.save(hiking3);
        outdoorRepo.save((Outdoor)hiking3);
        Activity hiking4 = new Outdoor("OUT04","Kilimli Koyu Trekking Parkuru","Hiking","OUT04.jpg",4.3,"OUT04path","https://maps.app.goo.gl/M7DxUatTDagc4N468");
        hiking4.addTimeSlot(LocalTime.of(5, 0, 0));
        hiking4.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(hiking4);
        outdoorRepo.save((Outdoor)hiking4);
        Activity hiking5 = new Outdoor("OUT05","Validebağ Korusu","Hiking","OUT05.jpg",4.6,"OUT05path","https://maps.app.goo.gl/rfVuDNCtv7peyUeE7");
        hiking5.addTimeSlot(LocalTime.of(5, 0, 0));
        hiking5.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(hiking5);
        outdoorRepo.save((Outdoor)hiking5);

        Activity camp1 = new Outdoor("OUT06","Elmasburnu Tabiat Parkı","Camping","OUT06.jpg",4.2,"OUT06path","https://maps.app.goo.gl/HGoNtxKrGJoXCApS8");
        camp1.addTimeSlot(LocalTime.of(5, 0, 0));
        camp1.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(camp1);
        outdoorRepo.save((Outdoor)camp1);
        Activity camp2 = new Outdoor("OUT07","Polonezköy Tabiat Parkı","Camping","OUT07.jpg",4.4,"OUT07path","https://maps.app.goo.gl/niisTBEDuBNkbdJE9");
        camp2.addTimeSlot(LocalTime.of(5, 0, 0));
        camp2.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(camp2);
        outdoorRepo.save((Outdoor)camp2);
        Activity camp3 = new Outdoor("OUT08","Ağva Kilimli Koyu","Camping","OUT08.jpg",3.9,"OUT08path","https://maps.app.goo.gl/WpmrfXShyokg3DB17");
        camp3.addTimeSlot(LocalTime.of(5, 0, 0));
        camp3.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(camp3);
        outdoorRepo.save((Outdoor)camp3);
        Activity camp4 = new Outdoor("OUT09","Ayhan Şahenk Sevgi Ormanı","Camping","OUT09.jpg",4.2,"OUT09path","https://maps.app.goo.gl/4DZ7XSe2AtA3dVmW9");
        camp4.addTimeSlot(LocalTime.of(5, 0, 0));
        camp4.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(camp4);
        outdoorRepo.save((Outdoor)camp4);
        Activity camp5 = new Outdoor("OUT10","Çiftalan Kamping","Camping","OUT10.jpg",4.5,"OUT10path","https://maps.app.goo.gl/TNwrwCKBHE5Aw5Qv8");
        camp5.addTimeSlot(LocalTime.of(13, 0, 0));
        camp5.addTimeSlot(LocalTime.of(10, 0, 0));
        activityRepo.save(camp5);
        outdoorRepo.save((Outdoor)camp5);

        Activity bike1 = new Outdoor("OUT11","Caddebostan Sahili","Biking","OUT11.jpg",4.6,"OUT11path","https://maps.app.goo.gl/VQW963tfoCLNKgj79");
        bike1.addTimeSlot(LocalTime.of(5, 0, 0));
        bike1.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(bike1);
        outdoorRepo.save((Outdoor)bike1);
        Activity bike2 = new Outdoor("OUT12","Büyükada","Biking","OUT12.jpg",4.5,"OUT12path","https://maps.app.goo.gl/hntcsqHzeofo8FZj6");
        bike2.addTimeSlot(LocalTime.of(7, 0, 0));
        bike2.addTimeSlot(LocalTime.of(23, 0, 0));
        activityRepo.save(bike2);
        outdoorRepo.save((Outdoor)bike2);
        Activity bike3 = new Outdoor("OUT13","Aydos Ormanı","Biking","OUT13.jpg",4.2,"OUT13path","https://maps.app.goo.gl/tuHyB8Wb4QcZuiyZ7");
        bike3.addTimeSlot(LocalTime.of(5, 0, 0));
        bike3.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(bike3);
        outdoorRepo.save((Outdoor)bike3);
        Activity bike4 = new Outdoor("OUT14","Bakırköy Sahil Parkı","Biking","OUT14.jpg",4.1,"OUT14path","https://maps.app.goo.gl/yZF4TbVkhv7kLtkF8");
        bike4.addTimeSlot(LocalTime.of(5, 0, 0));
        bike4.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(bike4);
        outdoorRepo.save((Outdoor)bike4);
        Activity bike5 = new Outdoor("OUT15","Belgrad Ormanı","Biking","OUT15.jpg",4.7,"OUT15path","https://maps.app.goo.gl/B9n4xKVhDQAvYZaZ7");
        bike5.addTimeSlot(LocalTime.of(5, 0, 0));
        bike5.addTimeSlot(LocalTime.of(23, 30, 0));
        activityRepo.save(bike5);
        outdoorRepo.save((Outdoor)bike5);

        Activity sight1 = new Outdoor("OUT16","Çamlıca Tepesi","Sightseeing","OUT16.jpg",4.7,"OUT16path","https://maps.app.goo.gl/NzcCYRPke2rv6Fa27");
        sight1.addTimeSlot(LocalTime.of(4, 0, 0));
        sight1.addTimeSlot(LocalTime.of(23, 30, 0));
        outdoorRepo.save((Outdoor)sight1);
        activityRepo.save(sight1);
        Activity sight2 = new Outdoor("OUT17","Pierre Loti","Sightseeing","OUT17.jpg",4.3,"OUT17path","https://maps.app.goo.gl/3m7rKaM5z4Zd3q117");
        sight2.addTimeSlot(LocalTime.of(8, 30, 0));
        sight2.addTimeSlot(LocalTime.of(23, 30, 0));
        outdoorRepo.save((Outdoor)sight2);
        activityRepo.save(sight2);
        Activity sight3 = new Outdoor("OUT18","Otağtepe Fatih Korusu","Sightseeing","OUT18.jpg",4.5,"OUT18path","https://maps.app.goo.gl/Hhc5zzQRC2fHKMrq5");
        sight3.addTimeSlot(LocalTime.of(8, 0, 0));
        sight3.addTimeSlot(LocalTime.of(17, 30, 0));
        outdoorRepo.save((Outdoor)sight3);
        activityRepo.save(sight3);
        Activity sight4 = new Outdoor("OUT19","Galata Kulesi","Sightseeing","OUT19.jpg",4.7,"OUT19path","https://maps.app.goo.gl/ZtoRZR2uKNih6RMc9");
        sight4.addTimeSlot(LocalTime.of(10, 0, 0));
        sight4.addTimeSlot(LocalTime.of(20, 0, 0));
        outdoorRepo.save((Outdoor)sight4);
        activityRepo.save(sight4);
        Activity sight5 = new Outdoor("OUT20","Mihrabat Korusu","Sightseeing","OUT20.jpg",3.9,"OUT20path","https://maps.app.goo.gl/uKAjjwcPp1QBDe2c6");
        sight5.addTimeSlot(LocalTime.of(8, 0, 0));
        sight5.addTimeSlot(LocalTime.of(23, 30, 0));
        outdoorRepo.save((Outdoor)sight5);
        activityRepo.save(sight5);
        

        logger.info("Welcome to Otio!");
    }
}
